# Generated by Django 5.2.3 on 2025-07-17 01:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile_images/default_img.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
