# Generated by Django 5.2.3 on 2025-07-07 16:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='asset',
            field=cloudinary.models.CloudinaryField(blank=True, default='events_asset/default_img', max_length=255, null=True, verbose_name='image'),
        ),
    ]
